### PR TITLE
Update zh-TW Localizable.strings

### PR DESCRIPTION
**Pull request by Neo1102**
Correct translation errors

### CODE REVIEW

**Review by Froxcey — APPROVED** [review]
Looks much better, the original translation are too much of a direct translation. 

看起來好很多，原本的看起來很一比一。

vibe

**Comment by Neo1102** [comment]
Both Hong Kong and Taiwan use Traditional Chinese, but the syntax and wording may differ slightly due to local cultural differences. 
Before a Hong Kong native can maintain the translation, my translation can be updated in the Hong Kong localization file in sync. 
In theory, most Hong Kong people should be able to understand it.

**Comment by Liam0205** [comment]
@Froxcey 
Yes indeed. Because I have never really lived in Hong Kong and Taiwan, I can only use my experience to do traditional Chinese translation (Hong Kong and Taiwan). Mistakes are inevitable. If there are friends from Hong Kong or Taiwan who can do it in person, that's of course the best.

是的。因为我并未在港台真正生活过，所以只能凭借已有的经验去做繁体中文的翻译（港、台）。错漏在所难免。如果有香港或者台湾的朋友能亲自出手，那当然最好。

**Comment by sourcelocation** [comment]
Thanks

**Pull request merged**
