### PR TITLE
update translations

### PR DESCRIPTION
**Pull request by cupiditys**

### CODE REVIEW

**Comment by Cryptiiiic** [comment]
@cupiditys fix the conflicts

**Comment by Cryptiiiic** [comment]
Ironic, that didn't fix anything

**Comment by cupiditys** [comment]
this is hard

**Comment by Cryptiiiic** [comment]
It's really not, look up a git tutorial

**Comment by cupiditys** [comment]
someone already did most of the changes i did but i added changed few more things

**Comment by Cryptiiiic** [comment]
@cupiditys ugh, you messed up the spacing and lining of those files please fix

**Comment by cupiditys** [comment]
which file, I don't see anything wrong

**Comment by Cryptiiiic** [comment]
@cupiditys there, now see if thats all the changes Files Changed tab

**Comment by cupiditys** [comment]
that was repeated for some reason i just realized

**Comment by Cryptiiiic** [comment]
@cupiditys ok, if everything is good I will merge

**Comment by cupiditys** [comment]
yea it looks fine but I'm not sure why you added commit with like 6k changes? it seems weird but I don't know

**Comment by Cryptiiiic** [comment]
@cupiditys I merged master into your fork because you still had fugu 15 base

**Review by Cryptiiiic — APPROVED** [review]

**Pull request merged**
