### PR TITLE
[Translation][zh_*] follow up latest changes on master, and more.

### PR DESCRIPTION
**Pull request by Liam0205**

### CODE REVIEW

**Comment by Liam0205** [comment]
@sourcelocation again, from #33 . Please kindly consider an approve of merge.

> Although they all use Chinese characters, there are slight differences in word usage and character gylphs in different regions (Mainland China, Hong Kong, Taiwan, Singapore, etc.). Therefore, `zh_Hans` alone is not enough, we need `zh_CN`, `zh_HK`, `zh_TW`, and so on... Thus this PR.

`zh_Hans` does not covers all simplified Chinese areas, thus we **DO NEED** multiply version of localization file. Also, @xiangfeidexiaohuo as a noun, reboot userspace should be translated to `用户空间重启`, and as a verb, it should be translated to `重启用户空间`.

**Comment by sourcelocation** [comment]
Thank you for the corrections and additional changes!

**Comment by Liam0205** [comment]
> Thank you for the corrections and additional changes!

My pleasure : )

**Comment by Liam0205** [comment]
@sourcelocation BTW, `zh_CN.lproj` might need to be added to source in XCode again. As it was removed before.

**Pull request merged**
