### PR TITLE
Add dutch translations

### PR DESCRIPTION
**Pull request by daniellwdb**

### CODE REVIEW

**Review by sourcelocation — CHANGES_REQUESTED** [review]
0BA8CE7B-7578-45BF-92D1-977CF788F74E
Thanks for translation. Can you please fix this?

**Comment by sourcelocation** [comment]
677DECA6-766D-44F7-AAB9-6CA99257832B
Here’s in more detail

**Comment by daniellwdb** [comment]
Issue 1: I think "logboek" does not represent the technical meaning, rather something a user keeps track of.

Issue 5: I think this is a question to you since it's in the English translation as well. I guess you're referring to the app icon if applicable?

**Comment by sourcelocation** [comment]
EA17C28A-282F-4CFC-98DE-F282A33D6ABF
B9F9C72A-CC70-4641-9D5C-4D6DBAF5BF40
images.githubusercontent.com/52459150/233687364-edbfcf78-b045-4af3-bcd0-e6f793355bea.jpeg)
15206102-D74E-4A29-9F22-42B75A3431F3

I love having Dutch friends lol

**Comment by sourcelocation** [comment]
82B1C1A0-0052-4283-9E85-88B2D9855E67
5183C54B-0024-4906-9E12-F31144C2E861
8AA84855-966D-4000-9035-5E07417D851D
D6C2F803-7AB8-4B49-B1BE-C144509743AB

**Comment by sourcelocation** [comment]
Yeah app icon by xerus

**Pull request merged**
