### PR TITLE
Implement the proc_for_pid() in a more stable way.

### PR DESCRIPTION
**Pull request by SongXiaoXi**
It seems that jailbreakd will call forkfix at runtime, which then invokes `proc_iterate()` to iterate through the `allproc` list. If a process dies or is created simultaneously, it may lead to a kernel panic.

A more stable approach is to only traverse the `allproc` list when jailbreakd initializes its own proc address for the first time. Then, for subsequent PIDs, `task_for_pid()` is used to obtain the task port, and the address of the task port is obtained through `itk_space` of the task self, finally `bsd_info` is used to obtain the proc address of the target process. Since kernel r/w operations use resources of the current process in kernel, accessing invalid addresses due to other random events is almost non-existent. The unsafe stage only occurs during the first traversal.

By the way, launchd does not have the task_for_pid-allow entitlement, so it can only use the proc_iterate method. (I'm confused as to why userspace reboot gets stuck when launchd calls `task_for_pid()`.)

Tested on iPad Pro A12Z running iOS 15.1 based on tag 1.0.0-beta.8.

### CODE REVIEW

**Comment by opa334** [comment]
Hmm if this is actually an issue then it might be a better idea to just kcall `proc_find`

**Comment by SongXiaoXi** [comment]
@opa334 However, `proc_find()` increases the reference count of the `proc`, which means `proc_rele()` needs to be kcall-ed at the appropriate position in the code. Moreover, if jailbreakd crashes, is killed, or exits (userspace reboot) during this time, the `proc` kernel resource will leak permanently. Of course, leaking is better than crashing, but it still has side effects.

As for the frequency of crashes, it should depend on the frequency of `fork` and the busyness of other processes. I used a similar method to implement a daemon a few years ago using `proc_iterate`, it would panic almost every day due to my frequent usage. However, in recent years, there have been no observable panics since switching to using `itk_space`.

**Comment by opa334** [comment]
You see, proc_for_pid is not only called by forkfix. It is called every single time a process starts and gets wx_allowed. I don't think using proc_find / proc_rele should be a big problem honestly.

**Comment by opa334** [comment]
Btw, what does this panic look like? Spinlock? While itk_space is definitely a solution too, I would try to avoid it due to launchd also needing this stability fix. I guess past jailbreaks were able to give launchd task-for-pid_allow using entitlement injection.

**Comment by SongXiaoXi** [comment]
The panic could manifest as a `Kernel data abort` or `element modified after free` error in the `proc` zone.

I'm thinking that since `launchd` also needs `proc_for_pid`, `kcall(proc_find)` is indeed the most suitable option, provided that the `kcall` primitive is stable enough. On the one hand, the kernel and `launchd` have the same lifecycle, and if `launchd` dies, the entire system will restart. On the other hand, using entitlement injection to grant `launchd` the `task-for-pid_allow` permission doesn't seem to be an easy task. So as long as the injected code does not have any leakage logic, it should be fine.

To minimize the amount of code changes, I believe that the implementation of `proc_for_pid` should be as follows:
```
proc_for_pid_kcall:
    proc_ptr = kcall(proc_find)
    kcall(proc_rele, proc_ptr)
    return proc_ptr
```
This way, the returned `proc_ptr` still retains the same semantics as the original `proc_for_pid`, and there is no need to check if there is any possibility of leakage in other code. Moreover, it is easy to fallback to the original `proc_for_pid`.

Both `proc_for_pid_kcall` and `proc_for_pid_itkspace` only have one unstable point, as you mentioned, the target process may die after `proc_for_pid` but before memory is patched. Can this be guaranteed by `SIGSTOP` of the new process? If so, there should be no UAF risk unless the user or another process sends `SIGKILL`.

**Comment by SongXiaoXi** [comment]
However, it looks like my device hasn't experienced any spinlock panics yet. I'll see if there's anything else I can help with. Thank you so much for your genius work!👍

**Pull request closed without merging**
