### PR TITLE
[Dopamine] work on UI: implement OTA update methods.

### PR DESCRIPTION
**Pull request by Liam0205**
@opa334 the missing OTA update methods. `: )`

### CODE REVIEW

**Comment by opa334** [comment]
Could you like... not?

I mean I see you're trying to help, but I don't understand half of what you're doing or why you're doing it and obviously if the fix was this easy I would have already implemented it.

Besides, I saw you're now posting releases on your fork, please stop... Dopamine is not in a state where anyone should use it, especially not end users.

**Comment by opa334** [comment]
Okay just forget it, I saw how much stuff you added to your fork already.

So I would at least appreciate it if you could keep this on the low until Dopamine is actually released. I don't know, but I assume chinese people are already using this, right?

After it is out, I would appreciate if you could at least try adding the stuff you did from a tweak, from a quick glimpse this seems mostly possible. Although the additional bindfs mount might be difficult.

**Comment by Liam0205** [comment]
Yes there does be a leak version in the Chinese Jailbreak community. But that’s not mine. 

For my version, only few people in a private group is now testing.

**Comment by Liam0205** [comment]
okay, see what happened on twitter yesterday. I’ll remove the releases on my fork to prevent potentially further spreading.

**Comment by Liam0205** [comment]
All Dopamine related on my fork have been removed.

**Pull request closed without merging**
