### PR TITLE
Dopamine for 17.0b1

### PR DESCRIPTION
**Pull request by m1zole**

### CODE REVIEW

**Comment by TheMasterOfMike** [comment]
Nice.

This should work up to 17.0b4 for arm64 by the way, nothing should be inherently stopping it.

**Comment by kok3shidoll** [comment]
This is an offset that is not currently used, but I think kernelStruct.pmap.type (for A10(X)) is 0x94 in 17.0b1

**Comment by m1zole** [comment]
Which did you means kernelStruct.pmap.type = 0x94 + pmapA11Adjust or kernelStruct.pmap.type = 0x94?

**Comment by opa334** [comment]
> Which did you means kernelStruct.pmap.type = 0x94 + pmapA11Adjust or kernelStruct.pmap.type = 0x94?

If it's 0x94 on A10 then it's 0x94 + adjust on A11

**Comment by m1zole** [comment]
Thanks!
So, it's the same iOS16.x, right?

**Comment by m1zole** [comment]
how about new one?

**Comment by xz1c** [comment]
Can it support arm64e A13 SE2 ios17b1？

**Review by Lukka1208 — APPROVED** [review]

**Pull request closed without merging**
